name:           symfony-austria
description:    ""
autoload:
    psr-0:
        '': src/
minimum-stability: dev
authors:
  - name:       Gizela
    email:      cwikiel.g@gmx.net

repositories:
  - type: composer
    url: 'http://satis.c33s.net'

require:
    php:                                                '>=5.3.2'
    
    ext-iconv:                                          '*'
    ext-intl:                                           '*'
    
    igorw/composer-yaml:                                dev-master
    c33s/symfony-standard:                              2.1.*
    c33s/propel:                                        1.0.*
    
    #c33s/develop:                                       1.0.*
    #c33s/design:                                        1.0.*
    #friendsofsymfony/user-bundle:                       dev-master
    
scripts:
    post-install-cmd:
        - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap'
#        - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache'
#        - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets'
    post-update-cmd:
        - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap'
#        - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache'
#        - 'Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets'
config:
    bin-dir: bin

extra:
    symfony-app-dir: app
    symfony-web-dir: web
